spring:
  application:
    name: eureka-client-app-d

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  # instance:
  #   preferIpAddress: true # Optional, for preferring IP address in registration