spring:
  application:
    name: eureka-client-app-a

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  # instance:
  #   preferIpAddress: true # Optional, for preferring IP address in registration